name: Create Issue Branch

on:
  issues:
    types: [opened]  # 이슈가 열릴 때 트리거

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branchName: chistock-${{ github.event.issue.number }}-${{ github.event.issue.title | replace: ' ', '-' }}  # # 제거하고 - 사용
          autoCloseIssue: true
          openDraftPR: true
          copyIssueLabelsToPR: true
          copyIssueAssigneeToPR: true
          branches: |
            - label: 🐛 Bug
              prefix: bugfix/
            - label: 🩹 Simple Fix
              prefix: bugfix/
            - label: 🚨 HOTFIX
              prefix: hotfix/
            - label: 👷 CI
              prefix: env/
            - label: ⚙️ Setting
              prefix: env/
            - label: 💄 Design
              prefix: feature/
            - label: ✨ Feature
              prefix: feature/
            - label: ♻️ Refactor
              prefix: feature/
            - label: ✅ Test
              prefix: feature/
            - label: 📝 Document
              prefix: docs/
